# Generated by Django 5.1.5 on 2025-06-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_servicemedia_description_alter_servicemedia_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
            preserve_default=False,
        ),
    ]
