# Generated by Django 5.1.5 on 2025-06-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_servicemedia_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
    ]
