# Generated by Django 5.1.5 on 2025-06-24 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_servicemedia_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemedia',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicemedia',
            name='media_type',
        ),
        migrations.AlterField(
            model_name='servicemedia',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.service'),
        ),
    ]
