# Generated by Django 5.1.5 on 2025-06-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_studiocontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudioContact',
        ),
    ]
