# Generated by Django 5.1.5 on 2025-07-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_studiocontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudioContact',
        ),
    ]
