# Generated by Django 5.1.5 on 2025-07-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_studiocontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemedia',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
