# Generated by Django 5.1.5 on 2025-07-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_servicemedia_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
