# Generated by Django 5.1.5 on 2025-07-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='mobile',
            field=models.IntegerField(max_length=15),
        ),
    ]
