# Generated by Django 5.1.5 on 2025-07-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_contactmessage_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
