# Generated by Django 5.1.5 on 2025-07-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_contactmessage_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('extra_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('hours', models.CharField(max_length=100)),
            ],
        ),
    ]
